spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ufoldb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ufoluser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ufolpassword}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.devtools.restart.enabled=true
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.disable-swagger-default-url=true
server.servlet.session.timeout=15m
server.port=8080
spring.application.name=ufol-app
